# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "M699ZZX5DB",
      issuer_id: "ce445f08-0325-4fd7-84d1-7556bdb1ce09",
      key_filepath: "./AuthKey_M699ZZX5DB.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    # Ensure provisioning profiles and certificates are in place before building
    match(
      type: "appstore" # Type of profile, e.g., "appstore" for App Store distribution
    )

    # Build the app using the correct scheme and export method
    build_app(
      scheme: "fastLaneLogin",
      export_method: "app-store" # Corrected export method for App Store builds
    )

    # Upload the build to TestFlight or App Store Connect
    pilot(api_key: api_key)
  end
end
