# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :release do
    # Ensure provisioning profiles and certificates are in place before building
    match(type: "appstore")  

    # Build the app using the correct scheme and export method
    build_app(
      scheme: "fastLaneLogin",
      export_method: "app-store"  # Corrected export method for App Store builds
    )
  end
end