# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: "M699ZZX5DB",
      issuer_id: "ce445f08-0325-4fd7-84d1-7556bdb1ce09",
      key_filepath: "/Users/icode/Desktop/Projects/fastLaneLogin/fastlane/AuthKey_M699ZZX5DB.p8",
      duration: 1200,
      in_house: false
    )

    # Ensure provisioning profiles and certificates are in place before building
    match(
      type: "appstore",
      git_url:"git@github.com:umarfarooqnadeem/Certificates.git",
      keychain_password:".",
      app_identifier: "com.THEINCC.incubator.debug"  # Optional
    )

    # Build the app using the correct scheme and export method
    build_app(
      scheme: "fastLaneLogin",
      export_method: "app-store"
    )
    
    # Upload to TestFlight
    pilot(api_key: api_key)
  end
end
